-- Agent Platform new-project database schema (T02, DES-03 §4.2 / DES-11 / DES-14 / DES-16).
-- Owned exclusively by model/. A fresh, dedicated PostgreSQL database is
-- initialized from this file; an unknown or legacy schema is rejected, never
-- auto-dropped. This schema intentionally has no extension dependency: the
-- managed PostgreSQL role used by the platform cannot create extensions.
--
-- PostgreSQL 10 has neither a built-in UUID generator nor pgcrypto available
-- to this role. These identifiers are internal primary keys; authentication
-- secrets are generated by the application. Derive a UUID v4-shaped value
-- from PostgreSQL built-ins only, so a fresh database can be initialized with
-- ordinary DDL privileges.
CREATE OR REPLACE FUNCTION platform_uuid_v4() RETURNS uuid
LANGUAGE sql VOLATILE AS $$
    SELECT (
        substr(value, 1, 8) || '-' || substr(value, 9, 4) || '-4' ||
        substr(value, 14, 3) || '-' ||
        substr('89ab', floor(random() * 4)::integer + 1, 1) ||
        substr(value, 18, 3) || '-' || substr(value, 21, 12)
    )::uuid
    FROM (
        SELECT md5(
            random()::text || random()::text || clock_timestamp()::text ||
            pg_backend_pid()::text
        ) AS value
    ) AS source;
$$;

-- This schema is the authoritative DDL for the GORM entities declared across
-- the model package (DES-16 §18.3: entities and DDL reviewed together against
-- a temporary PostgreSQL for type/default/index/constraint agreement). The
-- schema_migrations row is inserted by the initializer, not here.

-- ---------------------------------------------------------------------------
-- Identity & authorization
-- ---------------------------------------------------------------------------
CREATE TABLE clients (
    id          uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    name        text        NOT NULL,
    -- R07 / D-14: per-Client concurrency quota (0 = unset, no limit). It is
    -- PostgreSQL-authoritative: ClaimStage locks the row, counts live stage
    -- claims and refuses to claim beyond the quota in the same transaction.
    concurrency_quota int       NOT NULL DEFAULT 0 CHECK (concurrency_quota >= 0),
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id          uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    client_id   uuid        NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    key_hash    text        NOT NULL,
    label       text        NOT NULL DEFAULT '',
    active      boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    revoked_at  timestamptz
);
CREATE INDEX api_keys_client_idx ON api_keys(client_id);

CREATE TABLE images (
    id               uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    client_id        uuid        NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    image_id         text        NOT NULL,
    repository       text CHECK (repository IS NULL OR (repository <> '' AND repository !~ '[@[:space:]]')),
    digest           text        NOT NULL CHECK (digest ~ '^sha256:[0-9a-f]{64}$'),
    contract_version text        NOT NULL,
    capabilities     jsonb       NOT NULL,
    entrypoint       jsonb       NOT NULL,
    state_format     text        NOT NULL DEFAULT '',
    status           text        NOT NULL DEFAULT 'validating',
    validation_ref   text        NOT NULL DEFAULT '',
    -- R07 / D-16: per-image dynamic warm-pool replicas (0 disables preheating).
    -- The legacy default_pool field is not used. Absolute per-image cap is 512, enforced by the admin API
    -- and the reconciler allocation, never by this CHECK.
    warm_pool_replicas int      NOT NULL DEFAULT 0 CHECK (warm_pool_replicas >= 0),
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT images_client_image_uq UNIQUE (client_id, image_id)
);

CREATE OR REPLACE FUNCTION prevent_image_identity_update() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.client_id IS DISTINCT FROM OLD.client_id OR NEW.image_id IS DISTINCT FROM OLD.image_id OR NEW.digest IS DISTINCT FROM OLD.digest OR NEW.repository IS DISTINCT FROM OLD.repository THEN
        RAISE EXCEPTION 'image identity is immutable';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER images_identity_immutable BEFORE UPDATE ON images FOR EACH ROW EXECUTE PROCEDURE prevent_image_identity_update();

CREATE TABLE platform_network_baselines (
    id uuid PRIMARY KEY DEFAULT platform_uuid_v4(), revision bigint NOT NULL CHECK (revision > 0), config_hash bytea NOT NULL CHECK (octet_length(config_hash) = 32), config jsonb NOT NULL CHECK (jsonb_typeof(config) = 'object'), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (revision)
);
CREATE TABLE platform_network_head (
    id boolean PRIMARY KEY DEFAULT true CHECK (id), active_revision_id uuid REFERENCES platform_network_baselines(id) ON DELETE RESTRICT, desired_revision_id uuid REFERENCES platform_network_baselines(id) ON DELETE RESTRICT, rollout_status text NOT NULL DEFAULT 'ready' CHECK (rollout_status IN ('applying','ready','failed')), error_summary text NOT NULL DEFAULT '' CHECK (length(error_summary)<=1024), updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO platform_network_head(id) VALUES (true);
CREATE TABLE network_config_revisions (
    id uuid PRIMARY KEY DEFAULT platform_uuid_v4(), scope text NOT NULL CHECK (scope IN ('client','image')), client_id uuid NOT NULL REFERENCES clients(id) ON DELETE RESTRICT, image_registration_id uuid REFERENCES images(id) ON DELETE RESTRICT, revision bigint NOT NULL CHECK (revision > 0), config jsonb NOT NULL CHECK (jsonb_typeof(config) = 'object'), config_hash bytea NOT NULL CHECK (octet_length(config_hash) = 32), created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT network_config_scope_image_ck CHECK ((scope='client' AND image_registration_id IS NULL) OR (scope='image' AND image_registration_id IS NOT NULL))
);
CREATE UNIQUE INDEX network_config_client_revision_uq ON network_config_revisions(client_id, revision) WHERE scope='client';
CREATE UNIQUE INDEX network_config_image_revision_uq ON network_config_revisions(image_registration_id, revision) WHERE scope='image';
CREATE TABLE client_network_heads (client_id uuid PRIMARY KEY REFERENCES clients(id) ON DELETE RESTRICT, active_revision_id uuid REFERENCES network_config_revisions(id) ON DELETE RESTRICT, desired_revision_id uuid REFERENCES network_config_revisions(id) ON DELETE RESTRICT, rollout_status text NOT NULL DEFAULT 'ready' CHECK (rollout_status IN ('applying','ready','failed')), error_summary text NOT NULL DEFAULT '' CHECK (length(error_summary)<=1024), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE image_network_heads (image_registration_id uuid PRIMARY KEY REFERENCES images(id) ON DELETE RESTRICT, active_revision_id uuid REFERENCES network_config_revisions(id) ON DELETE RESTRICT, desired_revision_id uuid REFERENCES network_config_revisions(id) ON DELETE RESTRICT, rollout_status text NOT NULL DEFAULT 'ready' CHECK (rollout_status IN ('applying','ready','failed')), error_summary text NOT NULL DEFAULT '' CHECK (length(error_summary)<=1024), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE runtime_profiles (
    id uuid PRIMARY KEY DEFAULT platform_uuid_v4(), image_registration_id uuid NOT NULL REFERENCES images(id) ON DELETE RESTRICT, platform_revision_id uuid NOT NULL REFERENCES platform_network_baselines(id) ON DELETE RESTRICT, network_revision_id uuid REFERENCES network_config_revisions(id) ON DELETE RESTRICT, image_ref text NOT NULL CHECK (image_ref ~ '^.+@sha256:[0-9a-f]{64}$'), template_name text NOT NULL, warm_pool_name text NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','ready','failed','disabled','revoked')), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX runtime_profiles_network_uq ON runtime_profiles(image_registration_id, platform_revision_id, network_revision_id) WHERE network_revision_id IS NOT NULL;
CREATE UNIQUE INDEX runtime_profiles_no_network_uq ON runtime_profiles(image_registration_id, platform_revision_id) WHERE network_revision_id IS NULL;
CREATE TABLE rollout_jobs (
    id uuid PRIMARY KEY DEFAULT platform_uuid_v4(), scope text NOT NULL CHECK (scope IN ('platform','client','image')), client_id uuid REFERENCES clients(id) ON DELETE RESTRICT, image_registration_id uuid REFERENCES images(id) ON DELETE RESTRICT, request_id text NOT NULL, platform_revision_id uuid REFERENCES platform_network_baselines(id) ON DELETE RESTRICT, network_revision_id uuid REFERENCES network_config_revisions(id) ON DELETE RESTRICT, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','failed','completed','cancelled')), attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0), error_summary text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, CONSTRAINT rollout_scope_ck CHECK ((scope='platform' AND client_id IS NULL AND image_registration_id IS NULL AND platform_revision_id IS NOT NULL AND network_revision_id IS NULL) OR (scope='client' AND client_id IS NOT NULL AND image_registration_id IS NULL AND platform_revision_id IS NOT NULL AND network_revision_id IS NOT NULL) OR (scope='image' AND client_id IS NOT NULL AND image_registration_id IS NOT NULL AND platform_revision_id IS NOT NULL AND network_revision_id IS NOT NULL))
);
CREATE UNIQUE INDEX rollout_platform_request_uq ON rollout_jobs(request_id) WHERE scope='platform';
CREATE UNIQUE INDEX rollout_client_request_uq ON rollout_jobs(client_id,request_id) WHERE scope='client';
CREATE UNIQUE INDEX rollout_image_request_uq ON rollout_jobs(image_registration_id,request_id) WHERE scope='image';
CREATE TABLE rollout_job_images (
    id uuid PRIMARY KEY DEFAULT platform_uuid_v4(), rollout_job_id uuid NOT NULL REFERENCES rollout_jobs(id) ON DELETE CASCADE, image_registration_id uuid NOT NULL REFERENCES images(id) ON DELETE RESTRICT, runtime_profile_id uuid REFERENCES runtime_profiles(id) ON DELETE RESTRICT, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','failed','completed','cancelled')), attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0), error_summary text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (rollout_job_id, image_registration_id)
);

CREATE OR REPLACE FUNCTION immutable_network_row() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'network revision/profile identity is immutable'; END $$;
CREATE TRIGGER platform_network_immutable BEFORE UPDATE OR DELETE ON platform_network_baselines FOR EACH ROW EXECUTE PROCEDURE immutable_network_row();
CREATE TRIGGER network_config_immutable BEFORE UPDATE OR DELETE ON network_config_revisions FOR EACH ROW EXECUTE PROCEDURE immutable_network_row();
CREATE OR REPLACE FUNCTION immutable_profile_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' OR NEW.image_registration_id IS DISTINCT FROM OLD.image_registration_id OR NEW.platform_revision_id IS DISTINCT FROM OLD.platform_revision_id OR NEW.network_revision_id IS DISTINCT FROM OLD.network_revision_id OR NEW.image_ref IS DISTINCT FROM OLD.image_ref THEN RAISE EXCEPTION 'runtime profile identity is immutable'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER runtime_profile_identity_immutable BEFORE UPDATE OR DELETE ON runtime_profiles FOR EACH ROW EXECUTE PROCEDURE immutable_profile_identity();

-- The two owner-validators are kept as separate trigger functions because each
-- trigger fires on a different table and references only columns that exist on
-- that table (PL/pgSQL resolves NEW.<field> at execution, so a shared function
-- touching a column absent from the firing table would fail).
CREATE OR REPLACE FUNCTION validate_network_revision_owner() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE owner_client uuid;
BEGIN
 IF NEW.scope='image' THEN SELECT client_id INTO owner_client FROM images WHERE id=NEW.image_registration_id; IF owner_client IS DISTINCT FROM NEW.client_id THEN RAISE EXCEPTION 'network revision owner mismatch'; END IF; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER network_revision_owner_check BEFORE INSERT OR UPDATE ON network_config_revisions FOR EACH ROW EXECUTE PROCEDURE validate_network_revision_owner();
CREATE OR REPLACE FUNCTION validate_runtime_profile_owner() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE owner_client uuid; rev_scope text; rev_client uuid; rev_image uuid;
BEGIN
 IF NEW.network_revision_id IS NOT NULL THEN SELECT scope,client_id,image_registration_id INTO rev_scope,rev_client,rev_image FROM network_config_revisions WHERE id=NEW.network_revision_id; SELECT client_id INTO owner_client FROM images WHERE id=NEW.image_registration_id; IF rev_scope='client' AND rev_client IS DISTINCT FROM owner_client THEN RAISE EXCEPTION 'runtime profile network owner mismatch'; ELSIF rev_scope='image' AND rev_image IS DISTINCT FROM NEW.image_registration_id THEN RAISE EXCEPTION 'runtime profile image mismatch'; END IF; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER runtime_profile_owner_check BEFORE INSERT OR UPDATE ON runtime_profiles FOR EACH ROW EXECUTE PROCEDURE validate_runtime_profile_owner();

-- ---------------------------------------------------------------------------
-- Runs, stages, contents, inputs, checkpoints
-- ---------------------------------------------------------------------------
CREATE TABLE runs (
    id                       uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    client_id                uuid        NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    image_registration_id    uuid        REFERENCES images(id) ON DELETE RESTRICT,
    network_revision_id      uuid        REFERENCES network_config_revisions(id) ON DELETE RESTRICT,
    req_id                   text        NOT NULL,
    req_fingerprint          bytea       NOT NULL,
    status                   text        NOT NULL DEFAULT 'queued',
    current_stage            int         NOT NULL DEFAULT 1,
    total_lifecycle_deadline timestamptz NOT NULL,
    cumulative_exec_seconds  bigint      NOT NULL DEFAULT 0,
    -- cumulative model request budget (DES-15 §17.4 / task book §1.4 step 7):
    -- pre-deducted per request across stages; the authoritative per-Run counter.
    model_request_count      bigint      NOT NULL DEFAULT 0,
    -- steering consumption state (DES-14 §16.4)
    next_steer_seq           bigint      NOT NULL DEFAULT 1,
    incorporated_through_seq bigint      NOT NULL DEFAULT 0,
    steer_count              int         NOT NULL DEFAULT 0,
    steer_content_bytes      bigint      NOT NULL DEFAULT 0,
    terminal_at              timestamptz,
    metadata_expires_at      timestamptz,
    cleanup_status           text        NOT NULL DEFAULT 'not_due',
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT runs_client_req_uq UNIQUE (client_id, req_id)
);
CREATE INDEX runs_client_status_idx ON runs(client_id, status);

CREATE TABLE run_stages (
    id                    uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    run_id                uuid        NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    runtime_profile_id    uuid        REFERENCES runtime_profiles(id) ON DELETE RESTRICT,
    stage_no              int         NOT NULL,
    fence                 bigint      NOT NULL,
    owner                 text        NOT NULL DEFAULT '',
    lease_expires_at      timestamptz,
    phase                 text        NOT NULL DEFAULT 'preparing',
    attempt               int         NOT NULL DEFAULT 0,
    launch_started        boolean     NOT NULL DEFAULT false,
    execution_id          text        NOT NULL DEFAULT '',
    started_at            timestamptz,
    budget_remaining_secs bigint      NOT NULL DEFAULT 0,
    pod_ref               text        NOT NULL DEFAULT '',
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT run_stages_run_stage_uq UNIQUE (run_id, stage_no)
);
CREATE UNIQUE INDEX run_stages_run_fence_idx ON run_stages(run_id, fence);

CREATE TABLE run_contents (
    id          uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    run_id      uuid        NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    stage_no    int         NOT NULL DEFAULT 0,
    kind        text        NOT NULL,
    ciphertext  bytea       NOT NULL,
    key_version int         NOT NULL,
    expires_at  timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX run_contents_run_kind_idx ON run_contents(run_id, kind);

CREATE TABLE checkpoints (
    id          uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    run_id      uuid        NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    stage_no    int         NOT NULL,
    fence       bigint      NOT NULL,
    object_ref  text        NOT NULL,
    sha256      text        NOT NULL,
    size_bytes  bigint      NOT NULL,
    state_format text       NOT NULL DEFAULT '',
    verified    boolean     NOT NULL DEFAULT false,
    referenced  boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE run_inputs (
    id                uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    run_id            uuid        NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    stage_no          int         NOT NULL,
    input_id          text        NOT NULL,
    kind              text        NOT NULL,
    state             text        NOT NULL DEFAULT 'pending',
    answer_hmac       bytea,
    checkpoint_id     uuid        REFERENCES checkpoints(id) ON DELETE SET NULL,
    answer_content_id uuid        REFERENCES run_contents(id) ON DELETE SET NULL,
    input_deadline    timestamptz NOT NULL DEFAULT 'infinity',
    options           jsonb       NOT NULL DEFAULT '[]',
    created_at        timestamptz NOT NULL DEFAULT now(),
    answered_at       timestamptz,
    CONSTRAINT run_inputs_run_input_uq UNIQUE (run_id, input_id)
);

-- ---------------------------------------------------------------------------
-- Outbox (reliable task & key-event delivery), DES-03 §4.3 / DES-09 §10.2
-- ---------------------------------------------------------------------------
CREATE TABLE outbox (
    id           bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id     uuid        NOT NULL,
    run_id       uuid,
    stage_no     int         NOT NULL DEFAULT 0,
    fence        bigint      NOT NULL DEFAULT 0,
    topic        text        NOT NULL,
    status       text        NOT NULL DEFAULT 'pending',
    payload_ref  uuid        REFERENCES run_contents(id) ON DELETE SET NULL,
    retry_at     timestamptz,
    claim_token  uuid,
    claimed_until timestamptz,
    expires_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT outbox_event_id_uq UNIQUE (event_id)
);
CREATE INDEX outbox_ready_idx ON outbox(status, retry_at) WHERE status = 'pending';
CREATE INDEX outbox_claim_expiry_idx ON outbox(claimed_until) WHERE status = 'processing';

-- ---------------------------------------------------------------------------
-- Steering (execution-time guidance), DES-14 §16.4
-- ---------------------------------------------------------------------------
CREATE TABLE run_steers (
    id                 uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    client_id          uuid        NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    run_id             uuid        NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    steer_id           text        NOT NULL,
    seq                bigint      NOT NULL,
    content_id         uuid        REFERENCES run_contents(id) ON DELETE SET NULL,
    content_hash       bytea,
    status             text        NOT NULL DEFAULT 'pending',
    reason_code        text,
    accepted_at        timestamptz NOT NULL DEFAULT now(),
    incorporated_at    timestamptz,
    incorporated_stage int,
    CONSTRAINT run_steers_client_run_steer_uq UNIQUE (client_id, run_id, steer_id),
    CONSTRAINT run_steers_run_seq_uq UNIQUE (run_id, seq)
);
CREATE INDEX run_steers_pending_idx ON run_steers(run_id, status, seq);

CREATE TABLE steer_batches (
    id                     uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    run_id                 uuid        NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    batch_id               uuid        NOT NULL,
    execution_id           text        NOT NULL,
    stage_no               int         NOT NULL,
    fence                  bigint      NOT NULL,
    start_seq              bigint      NOT NULL,
    through_seq            bigint      NOT NULL,
    issued_at              timestamptz NOT NULL DEFAULT now(),
    acked_at               timestamptz,
    status                 text        NOT NULL DEFAULT 'issued',
    CONSTRAINT steer_batches_batch_id_uq UNIQUE (batch_id)
);
-- A run/execution/stage/fence may hold at most one un-acked issue batch: a
-- retry after an ACK response loss must return the same batch, never mint a
-- second one (DES-14 §16.3 / AC-25). Issuing is therefore decided by this
-- unique constraint + RowsAffected instead of a row lock.
CREATE UNIQUE INDEX steer_batches_active_issue_uq
    ON steer_batches(run_id, execution_id, stage_no, fence)
    WHERE status = 'issued';

-- ---------------------------------------------------------------------------
-- Cleanup jobs (DES-11 §12.3)
-- ---------------------------------------------------------------------------
CREATE TABLE cleanup_jobs (
    id             uuid        PRIMARY KEY DEFAULT platform_uuid_v4(),
    resource_kind  text        NOT NULL,
    internal_ref   text        NOT NULL DEFAULT '',
    due_at         timestamptz NOT NULL,
    status         text        NOT NULL DEFAULT 'pending',
    attempts       int         NOT NULL DEFAULT 0,
    last_safe_code text        NOT NULL DEFAULT '',
    claimed_until  timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    completed_at   timestamptz
);
CREATE INDEX cleanup_jobs_due_idx ON cleanup_jobs(status, due_at) WHERE status IN ('pending','failed');

-- ---------------------------------------------------------------------------
-- R07 platform warm-pool settings (D-16): the runtime-authoritative dynamic
-- preheat configuration. The row is a single-boolean-PK singleton; every field
-- is NULLable (unset = fall back to the process config default). An empty
-- database seeds it on first boot from environment values via
-- INSERT ... ON CONFLICT (id) DO NOTHING (never overwrites admin values on
-- restart). The reconciler reads this same row once per round so multiple
-- workers converge deterministically; chart values are never runtime
-- authoritative once the row exists.
-- ---------------------------------------------------------------------------
CREATE TABLE platform_settings (
    id            boolean     PRIMARY KEY DEFAULT true CHECK (id),
    budget        int         CHECK (budget IS NULL OR budget >= 0),
    max_per_image int         CHECK (max_per_image IS NULL OR max_per_image >= 0),
    default_pool  int         CHECK (default_pool IS NULL OR default_pool >= 0),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Schema versioning (T02 § 2): unknown/legacy schema must be rejected, never
-- auto-dropped. The version row is inserted by the initializer, not here.
-- ---------------------------------------------------------------------------
CREATE TABLE schema_migrations (
    version     int         PRIMARY KEY,
    applied_at  timestamptz NOT NULL DEFAULT now()
);
