from __future__ import annotations

CONTRACT_VERSION = "agent-platform-runtime/v1"

STATUS_OK = "ok"
STATUS_AWAITING_INPUT = "awaiting_input"
STATUS_ERROR = "error"
VALID_STATUS = {STATUS_OK, STATUS_AWAITING_INPUT, STATUS_ERROR}

DELIVERY_NOT_REQUESTED = "not_requested"
DELIVERY_EMPTY = "empty"
DELIVERY_UPLOADED = "uploaded"
VALID_DELIVERY = {DELIVERY_NOT_REQUESTED, DELIVERY_EMPTY, DELIVERY_UPLOADED}

INPUT_KIND_QUESTION = "question"
INPUT_KIND_CHOICE = "choice"
INPUT_KIND_APPROVAL = "approval"
VALID_INPUT_KINDS = {INPUT_KIND_QUESTION, INPUT_KIND_CHOICE, INPUT_KIND_APPROVAL}

ROLE_SYSTEM = "system"
ROLE_DEVELOPER = "developer"
ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"
ROLE_TOOL = "tool"
VALID_ROLES = {ROLE_SYSTEM, ROLE_DEVELOPER, ROLE_USER, ROLE_ASSISTANT, ROLE_TOOL}

CAP_EXEC = "execution"
CAP_EVENTS = "events"
CAP_CANCEL = "cancel"
CAP_PAUSE_RESUME = "pause_resume"
CAP_STEERING = "steering"
CAP_FILES = "files"
CAP_SKILLS = "skills"
CAP_OPENAPI = "openapi_tools"
CAP_MCP = "mcp_tools"
CAP_ARTIFACTS = "artifacts"

LEGACY_CORE_CAPABILITIES = [CAP_EXEC, CAP_EVENTS, CAP_CANCEL, CAP_PAUSE_RESUME, CAP_STEERING]
CORE_CAPABILITIES = LEGACY_CORE_CAPABILITIES + [CAP_FILES, CAP_SKILLS, CAP_OPENAPI, CAP_MCP, CAP_ARTIFACTS]
EXTENSION_CAPABILITIES = [CAP_FILES, CAP_SKILLS, CAP_OPENAPI, CAP_MCP, CAP_ARTIFACTS]
KNOWN_CAPABILITIES = set(CORE_CAPABILITIES) | set(EXTENSION_CAPABILITIES)

STEER_PENDING = "pending"
STEER_INCORPORATED = "incorporated"
STEER_NOT_APPLIED = "not_applied"
STEER_UNKNOWN = "unknown"

ERR_INVALID_REQUEST = "invalid_request"
ERR_INVALID_MESSAGES = "invalid_messages"
ERR_REQ_ID_CONFLICT = "req_id_conflict"
ERR_SANDBOX_IMAGE_UNAVAILABLE = "sandbox_image_unavailable"
ERR_CAPABILITY_UNSUPPORTED = "capability_unsupported"
ERR_CHECKPOINT_PERSIST_FAILED = "checkpoint_persist_failed"
ERR_CHECKPOINT_INVALID = "checkpoint_invalid"
ERR_RESUME_FAILED = "resume_failed"
ERR_EXECUTION_OUTCOME_UNKNOWN = "execution_outcome_unknown"
ERR_RESULT_BUNDLE_UPLOAD_FAILED = "result_bundle_upload_failed"
ERR_ARTIFACT_DESTINATION_REQUIRED = "artifact_destination_required"
ERR_RUNTIME_PROTOCOL_INVALID = "runtime_protocol_invalid"
ERR_AGENT_EXECUTION_FAILED = "agent_execution_failed"
ERR_RUN_CANCELLED = "run_cancelled"
ERR_RUN_EXPIRED = "run_expired"
ERR_EXECUTION_TIMEOUT = "execution_timeout"
ERR_RESOURCE_LIMIT_EXCEEDED = "resource_limit_exceeded"
ERR_EVENT_DELIVERY_FAILED = "event_delivery_failed"
ERR_PAYLOAD_TOO_LARGE = "payload_too_large"

ERR_INVALID_STEER = "invalid_steer"
ERR_STEER_CONFLICT = "steer_conflict"
ERR_STEER_LIMIT_EXCEEDED = "steer_limit_exceeded"
ERR_STEERING_CURSOR_CONFLICT = "steering_cursor_conflict"
ERR_RUNTIME_STATE_CONFLICT = "runtime_state_conflict"
ERR_STEERING_DELIVERY_FAILED = "steering_delivery_failed"
ERR_STEERING_CHECKPOINT_MISMATCH = "steering_checkpoint_mismatch"

STEER_ID_MAX_LEN = 128
STEER_CONTENT_MAX_BYTES = 16 * 1024
STEER_REQUEST_MAX_BYTES = 128 * 1024
STEER_MAX_PER_RUN = 128
STEER_CONTENT_TOTAL_MAX_BYTES = 1 * 1024 * 1024

MAX_RESOURCES_PER_TYPE = 32
MAX_ANSWER_CHOICES = 32
MAX_NETWORK_RULES = 32

DEFAULT_REMAINING_EXECUTION_SECONDS = 900
DEFAULT_CHECKPOINT_MAX_BYTES = 512 * 1024 * 1024

STEERING_MAX_RETRIES = 3
STEERING_BACKOFF = (1, 2, 4)

APP_ROOT = "/app"
INPUT_DIR = "/app/input"
WORKSPACE_DIR = "/app/workspace"
OUTPUT_DIR = "/app/output"
RUN_CONFIG_PATH = "/app/run.json"
RESULT_PATH = "/app/output/result.json"
CHECKPOINT_PATH = "/app/output/checkpoint.tar.gz"

DEFAULT_PORT = 8888
